### ISSUE TITLE
LimoNade Crashes Rack when changing number of SAMPLES ?

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#123]
When I try to change the 204 ? should that not read 256.
![Limon204](https://user-images.githubusercontent.com/46076474/63761497-8fe67800-c8c1-11e9-87c4-df92a809e9c7.jpg)
I start deleting the 4 and the zero and than rack crashes with this log info : 
> [25.203 fatal src/main.cpp:38] Fatal signal 22. Stack trace:
24: ZN4rack10appDestroyEv 0x456415
23: raise 0xfd6d16f0
22: abort 0xfd6d537c
21: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x6fc5f170
20: ZN10__cxxabiv111__terminateEPFvvE 0x6fc581b0
19: ZSt9terminatev 0x6fd302b0
18: _cxa_throw 0x6fd39080
17: ZSt24__throw_invalid_argumentPKc 0x6fd3a550
16: ZN17LIMONADETextField4drawERKN4rack6widget6Widget8DrawArgsE 0x42fc530
15: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
14: ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE 0x492234
13: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
12: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
11: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
10: ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE 0x4a7502
9: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
8: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
7: ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE 0x4a30f4
6: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
5: ZN4rack6Window3runEv 0x4594ca
4: main 0x5a41a0
3: main 0x5a41a0
2: main 0x5a41a0
1: BaseThreadInitThunk 0x77495560
0: RtlUserThreadStart 0x775f3840

W7 1.0.6

Peter.

**Comment by sebastien-bouffier** [comment]
Hi Peter,
Frame length is used when loading a wave-table.
By default I have set it to 2048 because a lot of available free wave-tables that I have gathered are made of 2048 samples cycles.
This module has a wave-table of 256 frames of 2048 samples.
When you set it to 204 and import a wave-table, liMonADe will truncate your sample in chunks of 204 samples and create as many frames as it can up to 256 frames by interpolating each chunk of 204 samples on the 2048 available per frame.
So lets say that your wave-table is made of 15 cycles of 204 samples, you will obtain 15 frames of 2048 samples, each frame being made of the interpolation of the 204 samples on its 2048 samples available.
If you change 204 to 2048 liMonADe doesn't make anything until you reload your wave-table.
If you have a 15 frames wave-table and ask liMonADe to perform a morphing it will relocate the 15 frames that are contiguous onto the 256 frames and morph the frames that are in between the ones you loaded.
I hope it makes sense since my english is far from being perfect and the approach I used for liMonADe may be unconventional. Let me know.

I did not manage to reproduce the bug when changing the frame length. I will try to fix it in the next version.

Best regards,
Seb

**Comment by Petervos2018** [comment]
Hi Seb,
Thanks again for the explanation and taking the time.
The problem on W7 is that that field is 204 and not 204(8).
When I load a fresh LiMonade it looks like the pic in post 1.
Normally I would not be bothered but I thought "let's change it", and then the error happened.

Something else I noticed, when I have a LiMonade in the patch, and I load that patch, it slows down the drawing speed of the initial load.
It looks like it drains a lot of GPU see #119  (Maybe you solved it but my French is not that BON) ;)

Other than that still loving you modules a lot,

Greeting Peter

**Comment by sebastien-bouffier** [comment]
thanks a lot for your interest Peter :)
I did not understand that framelength was 204 when opening a new instance of the module and then crashes when changing the value. 
I will try to fix it.
Cheers

**Comment by sebastien-bouffier** [comment]
You can disable the 3D wave-table rendering with the help of the "d" button on the top right area of the module. It may help.
That being said I do not know why you have 204 frame size by default .. still investigating.

**Comment by Petervos2018** [comment]
Hi Seb,
It helps a little when I disable the display but not a lot....EDIT more than I thought :)
I don't know where the 8 has gone either , No wait it's on the next row, the yellow line you see under the 2 is the top of the 8 but I'm not able to get 4 digits in the screen...
EDIT : Well I can !!! 
but its zoom dependant I have 3 digits at 74-75, 90-93, 106-107, and 122-123 % zoom.
Does this help ?

Greets Peter.

**Comment by sebastien-bouffier** [comment]
Hi, I changed the text editor width in 1.0.8
Under W10 the number of digits displayed doesn't change with zoom and I am not able to make happen the crash when changing the number of samples ...
Let me know if you see 2048 by default and if you still face the same issue when changing that number please.
Cheers

**Comment by Petervos2018** [comment]
Hi Seb,
I tried the new version, and the 2048 is clear on every zoom level (had some problems with 25%, just kidding it's way to small to read/see anything).

Removing the 2048 from the text field by deleting the 8,4,0,2 
keeps crashing Rack as soon as I try to remove the 2.

But I don't mind I don't think I'm ever going to change that number, 
"Ricky don't change that number" 

Now go and fix this #126  

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi 1.0.9 may fix your issue with framelength param

**Comment by Petervos2018** [comment]
Hi Seb, 1.0.9 did the trick !
Thank you so much.

Closing.
