### ISSUE TITLE
feature request of dTrOY: I hope to be able to select the gate specification of 0.4.0 with the right click menu

### ISSUE THREAD

**Issue by inubata** [sebastien-bouffier/Bidoo#13]
The gate specification seems to have changed at 0.5.0, but can you make the 0.4.0 gate specification usable?

0.4.0 has click noise when changing the gate value during play. However, I think the 0.4.0 play is more interesting.
It is good to select by right click.
Would that be possible?

**Comment by sebastien-bouffier** [comment]
Hello inubata, can you give me more details because I do not use v0.4.0 since a long time now and the gate part didn't change between all redesigns steps. Did it happened when moving the knob ? CV control ? both ? BTW I will take a look to what could have changed on that feature ... but to be honest I do not remember any noise on gate because it is not designed to make noise but to drive another unit..
Please give me details of the context ..

**Comment by inubata** [comment]
I'm sorry, I wasted your time.
I have misunderstood.

Apparently it seems to have happened with a combination of Rack (Version dev) and other modules.
I checked again at 0.5.0, but there was no problem.

Thank you for answering my question.
dTrOY is a great module.
Please continue to develop in the future.

**Comment by sebastien-bouffier** [comment]
Ok great to read that everything is working good.
