### ISSUE TITLE
bordL steps 16?

### ISSUE THREAD

**Issue by ghost** [sebastien-bouffier/Bidoo#144]
Hi I see 8 steps in the module but not 16. How do I enable all 16?

**Comment by sebastien-bouffier** [comment]
Hi @modman2019 ,
bordL and dTrOY are based on Roland 185, DU-SEQ and Metropolis sequencers (my understanding of how they behave since I do not own them ...) so they have 8 steps (pitch, slide etc...) and you can loop up to 16 steps or pulses on them.
Parameters and display are here
![image](https://user-images.githubusercontent.com/1842599/78995181-12b2ff00-7b42-11ea-80ff-4e285649feb0.png)
Steps allows you to specify your pattern length (if you trig Reset before the end of the pattern it will be reset whatever Steps value) and Count let you switch between steps and pulses count.
If you need to make patterns with more than 8 different steps you should take a look at zOù MAï ...
Hope it helps.
Best.

**Comment by ghost** [comment]
Thanks
