### ISSUE TITLE
8re at full CW CV1 or CV2 are 12volts

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#147]
OS (if applicable): win
Version (or "dev" if compiling from source): 1.1.5
It is ok actually? I just expect 10v) And the gate outputs seems like send pretty short trigger

**Comment by sebastien-bouffier** [comment]
Hi @vcvrackideas  
Thanks for your interest in my modules.
I added a param in order to chose between "gate" opened at 10V when step is active and "trig" that only send a pulse.
All CVs out are calibrated at 10V now.
Thanks again for your report it helps me to increase my modules quality.
I will provide a new version soon.
Best,
Seb

**Comment by sebastien-bouffier** [comment]
Hi, if the issue is fixed please close the thread.
Best.
