### ISSUE TITLE
Strange behavior of Zou Mai's STEPS knob

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#152]
OS (if applicable): win
Version (or "dev" if compiling from source): 1.1.8
It's really hard to explain by text, would be better to show you a video and yeah reset doesn't help and this behaves occasionally. It's not behavior of the knob actually but it affects behavior of wrong step and wrong starting and looping points
![zou mai test](https://user-images.githubusercontent.com/42435368/79989154-35390680-84b8-11ea-82c6-243bce44d552.gif)

**Comment by MaZe6K** [comment]
It's the same bug I reported here:
https://github.com/sebastien-bouffier/Bidoo/issues/148
But your video shows it better.
@sebastien-bouffier since you have the reset fixed, maybe you could make the step correlating to the sequence length send an internal reset instead of whatever you're doing now to change sequence length? Just an idea, thought it might help.

**Comment by sebastien-bouffier** [comment]
Hi, I am currently working on that issue. @MaZe6K I was already sending an internal reset but syncing with clock multipliers for "trim" was a nightmare. So I have a stable version that is able to multiply speed per x1 x2 x3 and x4 and I think it is enough at that time, other tempi can be managed from the outside clock module. Up to x16 was a bit too much :). I will push today and you will tell me if it is ok for you.
cheers

**Comment by vcvrackideas** [comment]
Thanks! But now sequence freezes (hangs) a bit on 7th step if 7 step is activated and 5th step if 5 step mode is activated...It looks like each of them want to play 6 steps instead of 5 or 8 steps instead of 7. And 4 instead of 3 as well

**Comment by sebastien-bouffier** [comment]
@vcvrackideas did you pull and build my last commit ?

**Comment by vcvrackideas** [comment]
> @vcvrackideas did you pull and build my last commit ?

Sure - speed is 1x-4x here) new version

**Comment by sebastien-bouffier** [comment]
mmm that is strange because I added that line of log 
`if (patterns[currentPattern].tracks[i].getCurrentTrig().index>7) std::cout << "missed" << '\n';` and if I set every track to a length <= 8 I never reach the 9th step (index=8) whatever reset is connected or not ... Could you send me your patch please ?
Here is mine for test 
[test.log](https://github.com/sebastien-bouffier/Bidoo/files/4532704/test.log)
It is a patch so please change the file extension to .vcv (I changed the extension because github does not allow .vcv attachments)

**Comment by vcvrackideas** [comment]
Ok Seb! Your patch is playing well. After changing clock module on Clkd I got also nice result! BUT when I switched on Speed x2 it starts stuck in 3, 5 and 7 steps mode on the last step...I think new speed knob has an issue
[test2.log](https://github.com/sebastien-bouffier/Bidoo/files/4535053/test2.log)

**Comment by MaZe6K** [comment]
yes, here too, if I set it to 3 steps on 2x or 4x speed it shows the same behaviour as before.

Another idea might be to ditch the different speeds altogether and replace them with individual gate inputs. Maybe this could even save a little bit of CPU? Again, just an idea...

**Comment by sebastien-bouffier** [comment]
Hi @MaZe6K thanks for your proposal and your interest in Zou :) I just pushed a new version and I hope this approach leads to better results. I am currently testing and I will release shortly. Best.

**Comment by sebastien-bouffier** [comment]
New push for patterns sync. Now I will rewrite all for performances ... :)

**Comment by sebastien-bouffier** [comment]
Hi @MaZe6K and @vcvrackideas  I just pushed a commit for zou, if you can test it before I ask vcv team a new release it would be great. Best.

**Comment by vcvrackideas** [comment]
Ok thanks! Now it works fine. And it seems to me CPU cons. is lower now isn't it? 
Also I found broken TOOLBOX buttons in terms of RND and even trig move left\right.

**Comment by sebastien-bouffier** [comment]
Hi, thanks for testing. Yes randomization is not implemented :) I will check for left right moves . Regarding CPU usage yes it should be less hungry since I have almost all redesigned. Object oriented code is not a good idea for real time so I have all changed for simple arrays, no more pointers too and intensive use of bit masking storage.

**Comment by sebastien-bouffier** [comment]
I still have issues on * and ? read modes ....

**Comment by sebastien-bouffier** [comment]
Read modes * and ? fixed, rand implemented. Regarding left and right moves they are only available for track and they seem to work. Best

**Comment by MaZe6K** [comment]
Sounds great! 
But I have to admit that I am no coder and not able to build something :)
If you could upload a Windows build I would test it, otherwise I'll wait for the next Library update.
Thank You for your efforts!

**Comment by sebastien-bouffier** [comment]
you can find a build for win here [https://github.com/sebastien-bouffier/Bidoo/releases/tag/1.1.21](https://github.com/sebastien-bouffier/Bidoo/releases/tag/1.1.21) you have to overwrite your Bidoo folder in rack path.

**Comment by vcvrackideas** [comment]
Thanks Seb! Works nice in this area now. Found another weird thing - check out behavior that sometimes happens while resetting, I mean those ultra rapids in the steps...
![weird reset](https://user-images.githubusercontent.com/42435368/80943689-769eaf80-8df0-11ea-96c4-9435703147b4.gif)

**Comment by sebastien-bouffier** [comment]
Lets say zou sees 1000 ticks between each clock pulses. So with your configuration zou goes backward 2 steps each 1000 ticks i.e. a step is 500 ticks long. If you reset after 200 ticks consumption and  you send a clock at the same time so the new base will be 200 ticks then zou goes backward 5 times faster before the next clock pulse occurs. If I ignore the clock signal when reset is fired the new base will be, with the same example, 1800 ticks long so zou would go slower before the next clock pulse. I do not know how to handle that kind of situation.

**Comment by sebastien-bouffier** [comment]
Hi, if you consider that the bug is fixed please close the thread. 
Best.
