### ISSUE TITLE
Ramp function in ACnE

### ISSUE THREAD

**Issue by MelchiorDussol** [sebastien-bouffier/Bidoo#165]
OS : Windows 10

Hello, 
the Ramp fonction is not working when I navigate between snapshots. The change is very brutal with no transition.
Is the function not implemented yet ? Or maybe I don't understand the goal of this function.

Thanks a lot,

**Comment by sebastien-bouffier** [comment]
Hi, it is designed in order to avoid clicks and to make smooth transitions so it seems broken. I will fix it.

**Comment by MelchiorDussol** [comment]
ok, awesome, it will be the ultimate mixer !
and thanks for your other modules ;)

**Comment by sebastien-bouffier** [comment]
Hi @MelchiorDussol ramp is now applied correctly between snapshots and I added the same behavior when soloing and muting.
I was not using solo and mute intensively and I noticed that they could produce clicks too. Let me know if your issue is fixed when 1.1.28 will be released by the module team.
Best.
