### ISSUE TITLE
(feature request) a CV input for the morph fader of Moire ?

### ISSUE THREAD

**Issue by nay-seven** [sebastien-bouffier/Bidoo#17]
OS (if applicable): all
Version : current 0.5

hello, a big thanks for your modules, 
all is in the title , would love to modulate this fader ;-)

**Comment by sebastien-bouffier** [comment]
Hello nay-seven, thanks and hope you have fun with them. I will take a look at that. Stay tuned.

**Comment by sebastien-bouffier** [comment]
Just have released the first step of MOiRE CV automation. It works but not as I would like. This module has been written for live use and everything is managed by the GUI. The consequence is that with this version, the resolution of morphing when automated is limited by the GUI refresh rate. I made this release because it doesn't threaten the initial behavior and you can start to do things with that. I will rewrite the code in order to fix this issue as soon as I can. I added CVs for both scenes and for the fader. Scenes updates are ok but fader update must be reworked. Best.

**Comment by nay-seven** [comment]
ok, i understand,
will try it as soon a friend compile a Mac version ;-)
will tell you

**Comment by nay-seven** [comment]
ok, a friend compile it for me, one thing i notice : the cv inputs, once connected block the knob moves ;-)
