### ISSUE TITLE
Question on Moire behavior (frozen knobs)

### ISSUE THREAD

**Issue by firolightfog** [sebastien-bouffier/Bidoo#174]
Knobs of Moire are getting frozen even by touching them. Is this a bug or a feature?

[Example of manually changing knob #8 and #7](https://youtu.be/BK1Yi9KR8BQ)

**Comment by sebastien-bouffier** [comment]
Hi I answered under your video. I wrote in the wiki that in order to cancel controls overriding you have to click on the morph button. That is the way I need MOiRE and πlOT to behave. When I override controls I need to let them play again the morphing at the same time so I made the decision to use the morph control which seemed to make sense (for me :) )

**Comment by firolightfog** [comment]
Thank you! Yes, it's the MORPH knob. 
Well, actually I think it's a good idea.
