### ISSUE TITLE
minor compiler warning...

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#19]
https://github.com/sebastien-bouffier/Bidoo/blob/7a21b8a7a33f1eef5f318ac2de20e4d09408472a/src/MOIRE.cpp#L221

> g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -Wsuggest-override -std=c++11 -c -o build/src/MOIRE.cpp.o src/MOIRE.cpp
src/MOIRE.cpp: In member function 'virtual void MOIREBidooLongSlider::onChange(rack::EventChange&)':
src/MOIRE.cpp:221:17: warning: unused variable 'parent' [-Wunused-variable]
    MOIREWidget *parent = dynamic_cast<MOIREWidget*>(this->parent);
                 ^~~~~~

**Comment by sebastien-bouffier** [comment]
Hi phdsg MOiRE has been rewritten mostly from scratch because I was unhappy with automation issues, choices that I made regarding not summing CV to controls which seemed a good idea at the beginning and most of all there was aliasing when morphing and I could stay with that !!!! :) I think that this message won't occur anymore.
Best
