### ISSUE TITLE
Feature request Zou Mai

### ISSUE THREAD

**Issue by omricohenmusic** [sebastien-bouffier/Bidoo#201]
OS (if applicable):
Version (or "dev" if compiling from source):
Hi!
Sorry to bother you about Zou Mai again but I had an idea that can help the workflow a bit. Is there a way to enter names for the tracks? So, for example, in the window where it says Pattern 1 : Track 1 it can say Pattern 1 : Kick, and then for other tracks different names instead of having the track number. It will be easier to follow which track is which voice. 
I know that in the Digital Sequencer XP from VoxGlitch there's a possibility to change this in the right click menu so changing the label. Maybe something like this can work? For example, having a Labels menu and there the ability to change the label for each track. 
What do you think?
Thanks again!
Omri

**Comment by sebastien-bouffier** [comment]
Hi that is a good idea. I cloned the VoxGlitch repo in order to take a look at the way he uses edits in menu and I discovered his plugins. I do not know if you tried πlOT but it has a lot of features in common with the Digital Sequencer XP. The main differences are that there is a built in sequencer/recorder, you can override values at run time and then recall the snapshot values just like on a elektron machinedrum with the function button, you can morph between scenes (or force jump per channel) and you can quantize all channels ... and more nice features (random etc...) :) In fact πlOT  is a MOiRE++
Track naming will be available in the next release.
And I hope you use mouse (over on light buttons for steps, tracks and pattern button for patterns) + keyboard shortcuts on Zoù it helps a lot to go faster (all shortcuts are displayed in the menu)
Best

**Comment by omricohenmusic** [comment]
Hey, thanks!
To be honest, I never really used the Sequencer XP I just saw that it has this feature and I thought it might help you in some way. But I will definitely check out uIOT!
And yes, I saw the shortcuts, super helpful.
Thanks again so much!
________________________________

**Comment by sebastien-bouffier** [comment]
Hi @omricohenmusic  just pushed 2.0.15 with that feature on Zou.
Best

**Comment by omricohenmusic** [comment]
That's amazing, thanks so much!On Jul 6, 2022 18:22, bidoo ***@***.***> wrote:
Hi @omricohenmusic  just pushed 2.0.15 with that feature on Zou.
Best
