### ISSUE TITLE
Suggestions for preset control and copy scene function!

### ISSUE THREAD

**Issue by jaffasplaffa** [sebastien-bouffier/Bidoo#218]
Hello :) 

Just discovered the πlOT module and like it a lot. Been looking for something like this, that makes it easy to set up many parameter. Awesome!

I'd like to make a couple of suggestions, which I think would make the modules even better ;) 

1. - Knob values and saving scenes
Another thing I am wondering a bit about, is when you for example change the value of a knob on scene 1 and you switch to scene 2, without saving scene 1, that knobs value will be stay the same on scene 2. So it actually show the value you set on scene 1. And if I then save scene 2, the value I actually set for scene 1 will then be saved to scene 2. To me a nice behaviour would be something like:

- Change the value of a knob on scene 1 and save it. The new value is now saved to scene 1.
- Change the value of a knob on scene 1 and switch to scene 2, without saving. The new value for the knob you set on scene 1 is lost and the knobs reflects the values of scene 2. If you change back to scene 1, the old value will be lost, cause scene 1 was not saved.

So basically you have to save a scene for the knob values to be stored, if you don't save the scene the knob value will be lost.

Maybe it's not intended to use the way I do, as a simple 16 knobs with presets/scenes module. I don't use morph between scenes, I only use it as 16 knobs with presets.

2.
Make a copy scene function. Self explanatory.

Hope it makes any sense. I've attached a screenshot of how I control the scene. Keep up the good work, just thought I'd share my thoughts. I am still learning the modules, so I might have misunderstood something, but I thought I'd swing it by you anyway. Maybe I can already do these ideas, just haven't discovered the way to do it yet.

Thanks on advance,
Jaffa

<img width="724" alt="Screenshot 2022-10-24 at 19 03 42" src="https://user-images.githubusercontent.com/14827192/197585297-7c3d8838-f183-47c1-a95f-f91a1d4a5ba6.png">

**Comment by sebastien-bouffier** [comment]
Hi @jaffasplaffa 
I start with copy/paste scenes. 
The reason why it is "not implemented" is because you can chose a scene to copy in the "top scene" slot and push the morph button to its max value so all your controls are in line with your chosen scene (as in your pic) and select a destination in the "bottom scene" and save it ... so you have copied the top scene in the bottom one. You can do the same thing by choosing your scene to copy in the "bottom scene" and set the big red morph button to zero so all your controls are set to that scene values and then chose a destination in the "top scene" slot and save it, so you have copied the bottom scene into the top one.
Now regarding controls values that differ from saved scenes.
I designed πlOT in order to navigate thru sets of values (scenes) and at the same time being able to override them live.
That is the reason why when you edit a control it starts to blink, meaning that it is not linked to saved values in both top and bottom scene slots anymore and its value is not affected by the morphing process anymore too.
In order to let all overridden controls go back to their "normal behavior" i.e. follow the morphing process and scene changes the magic trick is to click on the big red morph button (I don't know if you are aware of Elektron Machine Drum when you use the Function+Extended button that reset all changes made on a preset that is a killing feature live ... that is the same with that trick on πlOT) or saving controls values in a scene.
So all that being said, if I understand correctly your need you would have to click on the big red button at the same time you change the scene.
What if I let you chose per control if you want him to stay overridden or not when changing scene ?
Best,
Seb.

**Comment by sebastien-bouffier** [comment]
I realize that I never need to copy/paste a scene between banks. And as πlOT is currently working it is not possible to copy/paste scenes between banks so I might have to add a feature that allows that ...

**Comment by sebastien-bouffier** [comment]
Changes have been pushed.
Copy/paste is available on the scene selector.
By default all controls have the same behavior but you can toggle the "constant override" to false per control or on all controls via the menus and then controls jumps back to their saved values when you change scenes.

**Comment by sebastien-bouffier** [comment]
Released today. Hope you will enjoy those changes.

**Comment by jaffasplaffa** [comment]
Hey Sebastian ;) 

Argh.... I completely forgot about this for a long time, I am sorry! 

Wauw, I will surely give it a try and see if it can be used. 

Thank you so much for your effort!

Jakob
