### ISSUE TITLE
Issue with new plugin manager

### ISSUE THREAD

**Issue by martin-lueders** [sebastien-bouffier/Bidoo#23]
OS (if applicable): Win7
Version (or "dev" if compiling from source): Rack 0.5.1

Please, update your Makefile to the one from the Rack/Tutorial, to avoid the problems with the plugin manager. 

Happy to help if you run into problems.

Martin

**Comment by sebastien-bouffier** [comment]
Hello Martin I did not noticed those changes, I will check asap. Thanks for the update.

**Comment by sebastien-bouffier** [comment]
I made the changes, it seems to be fine. Please tell me if you think that I am correct so I create a new release and mend community json. I would like to make as few as possible pull request on community because it seems that Andrew and Jeremy spend a lot of time on merging pull requests.
Thanks again for your message, I was more in making music with Rack those days and I didn't paid attention to all those changes.

**Comment by martin-lueders** [comment]
Hi Sebastien,

you can test whether your build works by the usual method, i.e. copying the zip file into the Rack/plugin directory and then unzip yourself. Your Makefile looks alright and should work. Just make sure to update the Bidoo.json file in the community page.

**Comment by sebastien-bouffier** [comment]
done thanks again.
