### ISSUE TITLE
antN: crash with engine samplerates other than 44.1

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#62]
OS (if applicable): win7 mingw64
Version (or "dev" if compiling from source): dev

was playing around with changing rack's engine samplerates.
had a stream playing, then doubled the samplerate which doubled speed/pitch of the stream.
so far, so fine and funny :D 
next time i started rack it was still set to 88kHz. pressed play on antN -> crash:

still trying a few things... reporting back later.

**Comment by sebastien-bouffier** [comment]
Just tested and same result with this message [src/libmpg123/format.c:284] error: Unable to set up output format! Constraints: 44100, 22050 or 11025Hz.
So ... Why you can start with 44.1khz and change with artifacts -> because the output rate is set before the download/decode thread is launched so it doesn't affect mpg123 and it keeps on decoding @ 44.1 but frames are played faster. When you start higher than 44.1 mpg123 is not able to deliver frames ... I made some search and at the moment the sole solution seems to be this one -> to set a fixed output rate @ 44.1 in the plugin whatever the value of the real frequency is set to and doing the "upsampling" after the decoding stage.

**Comment by sebastien-bouffier** [comment]
Just pushed sample rate conversion. It works ... not very well but rack doesn't crash. It needs to be drastically improved.

**Comment by phdsg** [comment]
not crashing sounds good already... :)

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
