### ISSUE TITLE
Hello, where to find the release 0.6 for windows?

### ISSUE THREAD

**Issue by icet99** [sebastien-bouffier/Bidoo#69]
OS (if applicable):
Version (or "dev" if compiling from source):

**Comment by sebastien-bouffier** [comment]
still working on 0.6 compatibility my bad

**Comment by sebastien-bouffier** [comment]
it is coming shortly

**Comment by sebastien-bouffier** [comment]
released in ... release section :)

**Comment by sebastien-bouffier** [comment]
Dear musician/dev users I have rolled back to my previous way of linking curl for antN. After several tries I achieved to get closer to a static linking for curl but I didn't push because it was still not working. 
Btw there was something still unclear to me regarding this issue ... it was working on 0.5 in spite of not static linking. So I made the following test => rollback to my previous approach i.e. dyn link for curl and deployed my plugin on a W10 machine without any dev env installed. Under Rack 0.6 my 0.6.1 plugin works fine. I can build/link/run and play on my linux VM ... so the last thing to check is on mac os x .. If someone can build dist test on mac it would be great. 
I apologize for the delay but those lasts days have been quite complicated and I admit I could have made thing a little bit more fluid in terms of communication on FB but as you may know I am really reluctant to use that media for many good and bad reasons.

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
