### ISSUE TITLE
Module Idea/Concept inspired by ChUTE

### ISSUE THREAD

**Issue by phdsg** [sebastien-bouffier/Bidoo#7]
this is just an idea i had while fooling around with chute and i wanted to share it.

it's basically a rolling ball in a square area that triggers gates whenever
it collides with one of the borders. voltage according to the position it hits the wall.
ball receives pushes from a gate/trig with angle and acceleration set by cv inputs.
adjustable friction, amount of rebound, surface-area to ball-size ratio.

here's a visual mock-up:

![carambolage_mockup svg](https://user-images.githubusercontent.com/33329578/32983468-60bc22b6-cc95-11e7-94a8-95419b16ea30.png)

unfortunately can't code this myself, but maybe i get lucky and you like the idea.

**Comment by sebastien-bouffier** [comment]
Hello,
I have asked Jeremy Wentworth if his module Bouncy Ball will cover your idea.
But, good idea indeed :)

**Comment by phdsg** [comment]
yeah, i noticed this cpp file too, compiled and tried this module.
it's a ball falling to the ground,  bouncing a few times. very nice.
kind of similar to chute in that it uses gravity.
i was thinking more of a billard table scenario though.

**Comment by sebastien-bouffier** [comment]
Yep I understand that it is a kind of pool/snooker table that you have in mind. I did not tried to compile Jeremy's bouncing module but I have seen something like position x y and I thought it was in order to do something of that kind. Lets see his answer. His modules are neat and if he does something like that it will be great for sure. If he doesn't I will take a look.
At that time I am redesigning ACnE because it was far not optimized and I need more functionalities.

**Comment by phdsg** [comment]
look what jeremy did:
https://www.youtube.com/watch?v=79qnN7IIpMw

**Comment by sebastien-bouffier** [comment]
looks nice !
