### ISSUE TITLE
 library not found for -lglfw

### ISSUE THREAD

**Issue by qthegaijin** [sebastien-bouffier/Bidoo#71]
OS (if applicable): MacOS 10.12.6
Version (or "dev" if compiling from source): Dev

On Mac I am getting this message partway through the build: 
c++ -o plugin.dylib build/src/ACNE.cpp.o build/src/ANTN.cpp.o build/src/BAR.cpp.o build/src/BORDL.cpp.o build/src/Bidoo.cpp.o build/src/CANARD.cpp.o build/src/CHUTE.cpp.o build/src/CLACOS.cpp.o build/src/DFUZE.cpp.o build/src/DTROY.cpp.o build/src/DUKE.cpp.o build/src/FORK.cpp.o build/src/LATE.cpp.o build/src/LIMBO.cpp.o build/src/LOURDE.cpp.o build/src/MOIRE.cpp.o build/src/OUAIVE.cpp.o build/src/PERCO.cpp.o build/src/TIARE.cpp.o build/src/TOCANTE.cpp.o build/src/VOID.cpp.o build/src/ZINC.cpp.o build/src/dep/audiofile/AudioFile.cpp.o build/src/dep/pffft/pffft.c.o build/src/dep/filters/biquad.cpp.o build/src/dep/filters/smbPitchShift.cpp.o build/src/dep/freeverb/allpass.cpp.o build/src/dep/freeverb/comb.cpp.o build/src/dep/freeverb/revmodel.cpp.o dep/lib/libmpg123.a dep/lib/libcurl.a -Ldep/lib -lglfw -lcurl -lssl -shared -undefined dynamic_lookup -stdlib=libc++ -mmacosx-version-min=10.7
ld: library not found for -lglfw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [plugin.dylib] Error 1

Any ideas?

**Comment by sebastien-bouffier** [comment]
try to make a `git submodule update --init --recursive` before make

**Comment by qthegaijin** [comment]
Same result doing that.

**Comment by sebastien-bouffier** [comment]
can you provide me with the list of files you have in your Bidoo/dep/lib please ... I whish I had a mac to avoid that kind of situation ...

**Comment by qthegaijin** [comment]
![screen shot 2018-04-01 at 12 44 53 am](https://user-images.githubusercontent.com/33133035/38171022-f59426fe-3545-11e8-9a54-f030d9a431ae.png)

This is what's in the folder. If your system is compatible, try hackintoshing on a spare drive.

**Comment by sebastien-bouffier** [comment]
I removed the link to the lib and I tested on my linux VM and it works ... try to pull my last push and tell me if it works on sierra

**Comment by qthegaijin** [comment]
That worked! It spat out a bunch of warnings at the end about lubcurl being for a different version of OSX but all the modules are working now! Awesome work!

![screen shot 2018-04-01 at 1 34 24 am](https://user-images.githubusercontent.com/33133035/38171350-027f9f7c-354d-11e8-9aef-bb7e08c84195.png)

**Comment by sebastien-bouffier** [comment]
great :)

**Comment by sebastien-bouffier** [comment]
hello could you make a mac os x dist please ? I would like to add it to the last release

**Comment by qthegaijin** [comment]
Here ya go! 
[Bidoo.zip](https://github.com/sebastien-bouffier/Bidoo/files/1869763/Bidoo.zip)

**Comment by qthegaijin** [comment]
Just tried your 0.6.1 release build with mac, and it is a no-go on my system. I will attempt to build a new one and see if that works.

**Comment by qthegaijin** [comment]
Here is a fresh build for mac of 0.6.1 that works: 
[Bidoo_0.6.1_Mac_Working.zip](https://github.com/sebastien-bouffier/Bidoo/files/1869777/Bidoo_0.6.1_Mac_Working.zip)

**Comment by sebastien-bouffier** [comment]
Dear musician/dev users I have rolled back to my previous way of linking curl for antN. After several tries I achieved to get closer to a static linking for curl but I didn't push because it was still not working. 
Btw there was something still unclear to me regarding this issue ... it was working on 0.5 in spite of not static linking. So I made the following test => rollback to my previous approach i.e. dyn link for curl and deployed my plugin on a W10 machine without any dev env installed. Under Rack 0.6 my 0.6.1 plugin works fine. I can build/link/run and play on my linux VM ... so the last thing to check is on mac os x .. If someone can build dist test on mac it would be great. 
I apologize for the delay but those lasts days have been quite complicated and I admit I could have made thing a little bit more fluid in terms of communication on FB but as you may know I am really reluctant to use that media for many good and bad reasons.

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
