### ISSUE TITLE
antN 0.6.1 memory usage (Win10)

### ISSUE THREAD

**Issue by roboklops** [sebastien-bouffier/Bidoo#74]
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 0.6.1 (Bidoo-0.6.1-win.zip from release section)

antN seems tends to use up all the available memory (RAM) on my machine, then filling the 
pagefile.sys untill the system drive runs out of space and vcvrack crashes.

**Comment by sebastien-bouffier** [comment]
I am gonna look into this, stay tuned.

**Comment by sebastien-bouffier** [comment]
I think that I have found the source of that memory issue. I made a change not long ago to manage sampling rate modification and I used a temporary buffer for the sample rate converter. My bad the temp buffer was not deleted between mpeg decompression thread calls. The fix is pushed, tell me if you consider it fixed.
Best.

**Comment by roboklops** [comment]
Just compiled and tried the new build, works like a charm.

Thanx :)
