### ISSUE TITLE
Emile Crosstalk

### ISSUE THREAD

**Issue by midiguru23** [sebastien-bouffier/Bidoo#89]
Windows 7, VCV 0.6.2b. Emile 6.18. When I instantiate two or three separate Emiles and send them both gates (from Impromptu Clocked), I can listen to only one of them by turning its mixer channel up, and I'll get crosstalk from the second one into the audio output of the first one. If I remove the trigger from the second one, the audio output from the first one cleans up. It appears the separate instances are sharing a software data channel somehow.

**Comment by sebastien-bouffier** [comment]
Hello, I made the test with up to three instances and I cannot reproduce the issue. Could you send me your patch please ? FYI Emile has been redesigned in v6.19 because it was using too much cpu. I made the test with the new version and ... I have no issue running several instances. I will load my own png because at that stage I don't think it is png dependent.

**Comment by midiguru23** [comment]
I can't reproduce it this morning either. I didn't save the patch before, so this morning I made a very simple test patch, and it works perfectly. This may have been an auditory hallucination on my part. I'll try again with very simple .png files.

**Comment by sebastien-bouffier** [comment]
ok :)
