### ISSUE TITLE
Load sample into wavetable in liMonADe

### ISSUE THREAD

**Issue by Petervos2018** [sebastien-bouffier/Bidoo#93]
Hi Sebastien,
when you say : 
load sample into wavetable -  and - load sample into frame.
What kind of sample are we talking about here ?
I have a lot of single cycle wave files but I am not able to import/load them into liMonADe.

Here is a small example of the kind of files that won't work.
[AKWF_violin.zip](https://github.com/sebastien-bouffier/Bidoo/files/3098812/AKWF_violin.zip)
What am I doing wrong ?

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
Hi Peter,
I was about making a short video to show how to load your samples but W10 video capture doesn't record the file navigator ...
I made a test with your samples.
When I click on the double ~ button and load your first sample liMonADe creates a single frame with the wav because the sample is less or equal to 2048 samples
If I click on the single ~ button it does the same
So to load your full wave table I have to add several frames with the help of the + button then I select each frame with the green selector and then load the sample with the single ~ button
I will take a look if I can manage multi selection in the navigator :)
You can change the frame length from 2048 to 256 for example and you will see that if you load your first sample it will be cut into smaller frames but I don't think that your samples are designed to be used this way
I have found many wavetables where samples are n*2048 long and when you open those wav with the double ~ button it makes nice wavetables [02-Acid.zip](https://github.com/sebastien-bouffier/Bidoo/files/3112350/02-Acid.zip)
I hope it helps 
Greetings Seb.

**Comment by Petervos2018** [comment]
Hi Seb
Thanks for taking the time to explain the procedure to me, it is the first simple step that is not working for me. 
> When I click on the double ~ button and load your first sample liMonADe creates a single frame with the wav

So you can import the files I attached ?
So you see a visual representation of the wave in liMonADe ?
This is not what is happening on my Windows7 64bit system, there is no way I can load ANY wave or wavetable into liMonADe also the 02-Acid.wav is not doing anything for me, I just can't get them into liMoNAde.
I think there is some dependency for importing waves into liMonADe that is missing on my system ?

Greetings Peter.

**Comment by sebastien-bouffier** [comment]
I will take a look stay tuned

**Comment by Petervos2018** [comment]
Yes no problem they both load perfectly as seen on this pic :
![Loadsamplebidoo](https://user-images.githubusercontent.com/46076474/56701228-39441400-66fe-11e9-8a40-dde0d143c81a.jpg)
Sorry I did not see you edited your post, or I had answered sooner ;)

Greetings Peter

**Comment by sebastien-bouffier** [comment]
Hi Peter, sorry not to respond quickly but those days in France are quite complicated. I think it comes from threads management. In limonade I load samples via a dedicated thread. I will try to fix that asap.
Best.

**Comment by Petervos2018** [comment]
Thanks,
Take your time,
Peter.

**Comment by sebastien-bouffier** [comment]
Hi Peter, I pushed a modification on how buttons are working. Let me know if it works on W7.
Best,

**Comment by Petervos2018** [comment]
Hi Seb,
I'll let you know as soon as it is available from the plug-in manager.

Greetings Peter.

**Comment by Petervos2018** [comment]
As of the 24th May 2019 , I can load all kinds of Wav files and wavetables into liMonADe on Win7 !
Thank you Sebastien.
Love Peter ;)

**Comment by sebastien-bouffier** [comment]
Great :)
